const array = [
    {
        character:"37",
        afflatus:"Star",
        damage:"Mental",
        rarity: "six",
        number:"6",
        spell1:"Triangulation",
        spell1d:"1-target attack. Causes 140/210/350% Mental DMG, followed by an additional 40/60/100% Genesis DMG. Gains 1 stack of [Eureka].",
        spell2:"Curve Mapping",
        spell2d:"Mass Attack. Causes 70/105/175% Mental DMG to 2 enemies; additionally deals 40/60/100% Genesis DMG, and gives self a stack of [Sturdiness].",
        ult:"Realm of Numbers and Geometry",
        ultd:"Mass Buff. Gives all allies two stacks of [Numeral Perception]; Gains two stacks of [Enlightenment] and adds [Eureka] +2 to self.",
        portrait:"https://www.prydwen.gg/static/12a9276bf3b49bb3cdde0543129d129f/60b4d/7_icon.webp",
        splash:"https://www.prydwen.gg/static/4389e1262d7804f6fdb8920be1fcd89b/3cd29/64_full.webp"
    },
    {
        character:"",
        afflatus:"",
        damage:"",
        rarity: "",
        spell1:"",
        spell1d:"",
        spell2:"",
        spell2d:"",
        ult:"",
        ultd:"",
        portrait:"",
        splash:""
    },
    {
        character:"A Knight",
        afflatus:"Spirit",
        damage:"Reality",
        rarity: "six",
        spell1:"Justice",
        spell1d:"1-target attack. Deals 180/250/450% Reality DMG. If the target is defeated, Moxie +1/2/3 for self.",
        spell2:"Glory",
        spell2d:"Mass attack. Deals 150/150/225% Reality DMG to 2 enemies. Moxie +0/1/2 for self.",
        ult:"After AD 778",
        ultd:"Mass attack. Deals 400% Reality DMG to all enemies. If any target is defeated, then inflicts 1 stack of [Rousing Morale] on all allies.",
        portrait:"https://www.prydwen.gg/static/12a9276bf3b49bb3cdde0543129d129f/60b4d/7_icon.webp",
        splash:"https://www.prydwen.gg/static/23917698ee50c39ce4f056f87f477db2/3cd29/7_full.webp"
    },
    {
        character:"aliEn T",
        afflatus:"Star",
        damage:"Reality",
        rarity: "three",
        spell1:"The Witnessed",
        spell1d:"1-target attack. Deals 160/240/400% Reality DMG. If the target's current HP is above 50%, then deals 60/90/150% more Reality DMG.",
        spell2:"No Ill Intent",
        spell2d:"Self counter. Enter [Taunt] and DMG Taken -40/40/60% for 1/2/3 rounds.",
        ult:"Future Interstellar War: Prelude",
        ultd:"Mass attack. Deals 200% Reality DMG and inflicts 1 round of [Disarm] and [Silence] statuses on all enemies.",
        portrait:"https://www.prydwen.gg/static/6cf6ab0fdd35e80dcab03911bf5f9ecc/60b4d/40_icon.webp",
        splash:"https://www.prydwen.gg/static/b288265911861f365493edbb728b5b26/3cd29/40_full.webp"
    },
    {
        character:"An-an Lee",
        afflatus:"Plant",
        damage:"Reality",
        rarity: "six",
        spell1:"Taoist Rune",
        spell1d:"1-target attack. Deals 200/300/350% Reality DMG and inflicts [Daze] status for 0/0/1 round.",
        spell2:"Lily Nectar",
        spell2d:"Mass buff. DMG Dealt +15/20/30% and DMG Taken -15/20/30% for all allies. Lasts 2 rounds.",
        ult:"Scientific Ghost Buster",
        ultd:"Mass attack. Deals 400% Reality DMG to all enemies. The caster enters [Empower Incantation I] status for 2 rounds.",
        portrait:"https://www.prydwen.gg/static/0b86bc3c4710ab7fb76f3c30adfd1283/60b4d/0_icon.webp",
        splash:"https://www.prydwen.gg/static/e7e861f02dea05e98c915de2e91191ba/3cd29/0_full.webp"
    },
    {
        character:"APPLe",
        afflatus:"Star",
        damage:"Mental",
        rarity: "four",
        spell1:"Iridescent White",
        spell1d:"1-target attack. Deals 200/300/500% Mental DMG.",
        spell2:"Equal Amount of Light",
        spell2d:"1-target attack. Deals 150/225/375% Mental DMG. HP +(the caster's ATK x40/60/100%) for the ally with the lowest HP.",
        ult:"Insignifigant Achievements",
        ultd:"Mass attack. Deals 300% Mental DMG to all enemies. HP +(the caster's ATK x100%) for the ally with the lowest HP percentage.",
        portrait:"https://www.prydwen.gg/static/0b98cc2a98a7711123e8fa39ae258700/60b4d/30_icon.webp",
        splash:"https://www.prydwen.gg/static/b29310e67a7ec7d34248ea76c4958d7b/3cd29/30_full.webp"
    },
    {
        character:"Centurion",
        afflatus:"Beast",
        damage:"Reality",
        rarity: "six",
        spell1:"Victorious General",
        spell1d:"1-target attack. Deals 180/270/450% Reality DMG plus (the caster's Moxie x8/12/20%) Reality DMG.",
        spell2:"Outdoor Superstar",
        spell2d:"Mass attack. Deals 150/150/225% Reality DMG to 2 enemies. Moxie +0/1/2 to self.",
        ult:"Reality Show Premier",
        ultd:"Mass attack. Deals 300% Reality DMG and inflicts 1 stack of [Weakness] on all enemies.",
        portrait:"https://www.prydwen.gg/static/191228ad7e866fba991582aaafdce40b/60b4d/5_icon.webp",
        splash:"https://www.prydwen.gg/static/6ceccd2ad47168bd903b41b162eb6ad9/3cd29/5_full.webp"
    },
    {
        character:"",
        afflatus:"",
        damage:"",
        rarity: "",
        spell1:"",
        spell1d:"",
        spell2:"",
        spell2d:"",
        ult:"",
        ultd:"",
        portrait:"",
        splash:""
    },
    {
        character:"Melania",
        afflatus:"Beast",
        damage:"Mental",
        rarity: "six",
        spell1:"Silent Takedown",
        spell1d:"1-target attack. Deals 200/250/400% Mental DMG, Moxie by -0/1/1 for the target, and Moxie +0/0/1 for the caster. If the caster is in [Thief Master], this attack steals 1/2/3 additional Moxie from the target.",
        spell2:"Clockwork Rats",
        spell2d:"Mass attack. Deals 120/180/300% Mental DMG to 2 enemies. This attack enjoys Leech Rate +20%. If the caster is in [Thief Master], Moxie +1 and extra Leech Rate +30% for the caster.",
        ult:"Ridiculous Eyewitness Testimony",
        ultd:"1-target attack. Deals 650% Mental DMG. Inflicts 1 stack of [Thief Master] on the caster.",
        portrait:"https://www.prydwen.gg/static/4abbfd75d20606a1f0b2f2eb6ada77a2/60b4d/53_icon.webp",
        splash:"https://www.prydwen.gg/static/750d65af9aac71938bcd80f768aa1541/3cd29/53_full.webp"
    },
]

export{array}

